// =============================================
// Facebook AI Chatbot — Generated by FB Bot Builder
// Store: Wetopian Market BD
// =============================================

const express = require('express');
const bodyParser = require('body-parser');
const fetch = require('node-fetch');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const app = express();
app.use(bodyParser.json());

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const PAGE_TOKEN = process.env.FB_PAGE_TOKEN;
const VERIFY_TOKEN = process.env.FB_VERIFY_TOKEN;

// In-memory conversation history (per user)
const conversations = {};

const SYSTEM_PROMPT = `You are a helpful customer service AI assistant for "Wetopian Market BD", an online e-commerce store that sells: Woman sharee, Home decor , Eco products, electronics.

LANGUAGE: Always reply in English. If the customer writes in a different language, still reply in English (unless English is "same as customer", then match their language).

TONE: Be friendly and warm. yes, use relevant emojis occasionally.

STORE INFO:
- Business hours: Monday 10:00 AM - 6:00 PM Tuesday 10:00 AM - 6:00 PM Wednesday 10:00 AM - 6:00 PM Thursday 10:00 AM - 6:00 PM Friday CLOSED Saturday CLOSED Sunday 10:00 AM - 6:00 PM
- How to order: Contact us for ordering details

FAQs to answer accurately:
Q: Do you offer free delivery?
A: Yes! Free delivery on all orders above 500 EGP.

Q: How long does delivery take?
A: 2–4 business days within the city, 4–7 days outside.

Q: Can I return an item?
A: Yes, returns accepted within 7 days if the item is unused and in original packaging.

RULES:
- Keep replies concise (2-4 sentences max) and helpful
- If you don't know the answer, say: "যেকোনো জরুরি প্রয়োজনে আমাদের সরাসরি কল বা WhatsApp করুন এই নম্বরে  +8801805042626  কিছুক্ষন অপেক্ষা করুন। শীঘ্রই আমাদের একজন প্রতিনিধি আপনার সাথে যুক্ত হবে। ধন্যবাদ।"
- Never make up prices, stock levels, or delivery times you are not sure about
- Focus only on customer service — don't discuss unrelated topics
- If a customer wants to order, guide them through the ordering process step by step`;

// ── Webhook Verification ──────────────────
app.get('/webhook', (req, res) => {
  const mode = req.query['hub.mode'];
  const token = req.query['hub.verify_token'];
  const challenge = req.query['hub.challenge'];
  if (mode === 'subscribe' && token === VERIFY_TOKEN) {
    console.log('Webhook verified!');
    res.status(200).send(challenge);
  } else {
    res.sendStatus(403);
  }
});

// ── Receive Messages ──────────────────────
app.post('/webhook', async (req, res) => {
  const body = req.body;
  if (body.object !== 'page') return res.sendStatus(404);

  res.sendStatus(200); // Always ack immediately

  for (const entry of body.entry || []) {
    for (const event of entry.messaging || []) {
      if (!event.message || event.message.is_echo) continue;
      const senderId = event.sender.id;
      const text = event.message.text;
      if (!text) continue;

      // Build conversation history
      if (!conversations[senderId]) conversations[senderId] = [];
      conversations[senderId].push({ role: 'user', content: text });

      // Keep last 10 messages only
      if (conversations[senderId].length > 10)
        conversations[senderId] = conversations[senderId].slice(-10);

      try {
        const model = genAI.getGenerativeModel({
          model: 'gemini-1.5-flash',
          systemInstruction: SYSTEM_PROMPT
        });

        const history = conversations[senderId].slice(0, -1).map(m => ({
          role: m.role === 'assistant' ? 'model' : 'user',
          parts: [{ text: m.content }]
        }));

        const chat = model.startChat({ history });
        const result = await chat.sendMessage(text);
        const reply = result.response.text();
        conversations[senderId].push({ role: 'assistant', content: reply });

        await sendMessage(senderId, reply);
      } catch (err) {
        console.error('AI error:', err.message);
        await sendMessage(senderId, 'যেকোনো জরুরি প্রয়োজনে আমাদের সরাসরি কল বা WhatsApp করুন এই নম্বরে  +8801805042626  কিছুক্ষন অপেক্ষা করুন। শীঘ্রই আমাদের একজন প্রতিনিধি আপনার সাথে যুক্ত হবে। ধন্যবাদ।');
      }
    }
  }
});

// ── Send Message via Graph API ─────────────
async function sendMessage(recipientId, text) {
  const url = `https://graph.facebook.com/v19.0/me/messages?access_token=${PAGE_TOKEN}`;
  await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      recipient: { id: recipientId },
      message: { text },
      messaging_type: 'RESPONSE'
    })
  });
}

// ── Health Check ──────────────────────────
app.get('/', (req, res) => res.send('Bot is running! ✅'));

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));